version: '2'

services:
  bibbox-redcap:
    image: bibbox/redcap
    container_name:  bibbox-redcap
    restart: unless-stopped
    links:
      - bibbox-redcap-db:redcap-db
    ports:
      - "8095:80"
    depends_on:
      - bibbox-redcap-db
      - bibbox-redcap-data
    volumes_from: 
      - bibbox-redcap-data

  bibbox-adminer:
    image: adminer
    container_name: bibbox-redcap-adminer
    links:
      - bibbox-redcap-db:db
    restart: unless-stopped
    ports:
       - "8096:8080" 
    environment:
        ADMINER_DEFAULT_DB_DRIVER: mysql
        ADMINER_DEFAULT_DB_HOST: redcap-db
        ADMINER_DEFAULT_DB_NAME: redcap

  bibbox-redcap-db:
    image: mysql:8
    container_name: bibbox-redcap-db
    restart: unless-stopped
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusedeveninsidethecontainer
      - MYSQL_DATABASE=redcap
      - MYSQL_USER=redcap
      - MYSQL_PASSWORD=redcap4bibbox
    volumes_from: 
      - bibbox-redcap-data
    depends_on:
      - bibbox-redcap-data

  bibbox-redcap-data:
    image: busybox
    container_name: bibbox-redcap-data
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
      - ./data/www:/redcap_webroot
