version: '3'

networks:
  bibbox-default-network:
    external: true

services:
  dev-redcap-db:
    image: mariadb:10.6
    container_name: dev-redcap-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusedeveninsidethecontainer
      - MYSQL_DATABASE=redcap
      - MYSQL_USER=redcap
      - MYSQL_PASSWORD=redcap4bibbox
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/config/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf

  dev-redcap-apache:
    image: bibbox/redcap:v10-8-4
    command: "/bin/sh -c 'exec apache2-foreground'"
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - dev-redcap-db:redcap-db
    ports:
      - "8080:80"
    volumes:
      - ./data/html:/var/www/html
      - ./data/user-uploaded-documents:/opt/uploads
      - ./data/config/php-extensin.ini:/usr/local/etc/php/conf.d/php-extensin.ini
      - ./data/config/msmtprc:/etc/msmtprc
    environment:
      - DATABASE=redcap
      - DB_USER=redcap
      - DB_PASSWORD=redcap4bibbox

  bibbox-adminer:
    image: adminer:4.8.1
    container_name: bibbox-redcap-adminer
    networks:
      - bibbox-default-network

    links:
      - dev-redcap-db:db
    restart: unless-stopped
    ports:
       - "8096:8080" 
    environment:
        ADMINER_DEFAULT_DB_DRIVER: mysql
        ADMINER_DEFAULT_DB_HOST: db
        ADMINER_DEFAULT_DB_NAME: redcap

