version: '3.3'

networks:
  bibbox-default-network:
    external: true

services:
  dev-redcap-db:
    image: mariadb:10.6
    container_name: dev-redcap-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${ENV_MYSQL_DATABASE}
      - MYSQL_USER=${ENV_MYSQL_USER}
      - MYSQL_PASSWORD=${ENV_MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    env_file:
      - .env

  dev-redcap-apache:
    image: bibbox/redcap:v10-8-4
    command: "/bin/sh -c 'exec apache2-foreground'"
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - dev-redcap-db:db
    ports:
      - "9040:80"
    volumes:
      - ./data/html:/var/www/html
      - ./data/user-uploaded-documents:/opt/uploads
      - ./config/php-extensin.ini:/usr/local/etc/php/conf.d/php-extensin.ini
      - ./config/msmtprc:/etc/msmtprc

  dev-redcap-jobber:
    image: jobber:1.4-alpine3.11
    container_name: dev-redcap-jobber
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - dev-redcap-apache:redcapapp
    volumes:
      - ./config/.jobber:/home/jobberuser/.jobber
